In [1]:
import pandas as pd
import numpy as np

In [2]:
!wget https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv


--2023-10-02 22:48:19--  https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.108.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1475504 (1.4M) [text/plain]
Saving to: ‘data.csv.4’

data.csv.4          100%[===================>]   1.41M   972KB/s    in 1.5s    

2023-10-02 22:48:21 (972 KB/s) - ‘data.csv.4’ saved [1475504/1475504]



In [3]:
df = pd.read_csv("data.csv")

In [4]:
df.head()

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

In [5]:
df.columns = df.columns.str.lower().str.replace(' ', '_')

categorical_columns = list(df.dtypes[df.dtypes == 'object'].index)

for c in categorical_columns:
    df[c] = df[c].str.lower().str.replace(' ', '_')

In [6]:
df.head()

make       model  year             engine_fuel_type  engine_hp  \
0  bmw  1_series_m  2011  premium_unleaded_(required)      335.0   
1  bmw    1_series  2011  premium_unleaded_(required)      300.0   
2  bmw    1_series  2011  premium_unleaded_(required)      300.0   
3  bmw    1_series  2011  premium_unleaded_(required)      230.0   
4  bmw    1_series  2011  premium_unleaded_(required)      230.0   

   engine_cylinders transmission_type     driven_wheels  number_of_doors  \
0               6.0            manual  rear_wheel_drive              2.0   
1               6.0            manual  rear_wheel_drive              2.0   
2               6.0            manual  rear_wheel_drive              2.0   
3               6.0            manual  rear_wheel_drive              2.0   
4               6.0            manual  rear_wheel_drive              2.0   

                         market_category vehicle_size vehicle_style  \
0  factory_tuner,luxury,high-performance      compact         coupe   
1                     luxury,performance      compact   convertible   
2                luxury,high-performance      compact         coupe   
3                     luxury,performance      compact         coupe   
4                                 luxury      compact   convertible   

   highway_mpg  city_mpg  popularity   msrp  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

# Selected Feature 
- Make,
- Model,
- Year,
- Engine HP,
- Engine Cylinders,
- Transmission Type,
- Vehicle Style,
- highway MPG,
- city mpg,
- MSRP

In [7]:
df.columns

Index(['make', 'model', 'year', 'engine_fuel_type', 'engine_hp',
       'engine_cylinders', 'transmission_type', 'driven_wheels',
       'number_of_doors', 'market_category', 'vehicle_size', 'vehicle_style',
       'highway_mpg', 'city_mpg', 'popularity', 'msrp'],
      dtype='object')

In [8]:
features = [
    'make', 'model', 'year', 'engine_hp', 
    'engine_cylinders', 'transmission_type', 'vehicle_style', 'highway_mpg', 'city_mpg', 'msrp']

In [9]:
df = df[features]

In [10]:
df.rename({'msrp': 'price'}, axis=1, inplace=True)

In [11]:
df.head()

make       model  year  engine_hp  engine_cylinders transmission_type  \
0  bmw  1_series_m  2011      335.0               6.0            manual   
1  bmw    1_series  2011      300.0               6.0            manual   
2  bmw    1_series  2011      300.0               6.0            manual   
3  bmw    1_series  2011      230.0               6.0            manual   
4  bmw    1_series  2011      230.0               6.0            manual   

  vehicle_style  highway_mpg  city_mpg  price  
0         coupe           26        19  46135  
1   convertible           28        19  40650  
2         coupe           28        20  36350  
3         coupe           28        18  29450  
4   convertible           28        18  34500

In [12]:
df.isnull().sum()

make                  0
model                 0
year                  0
engine_hp            69
engine_cylinders     30
transmission_type     0
vehicle_style         0
highway_mpg           0
city_mpg              0
price                 0
dtype: int64

In [13]:
df.dtypes

make                  object
model                 object
year                   int64
engine_hp            float64
engine_cylinders     float64
transmission_type     object
vehicle_style         object
highway_mpg            int64
city_mpg               int64
price                  int64
dtype: object

In [14]:
df.fillna(0, inplace=True)

# Q1 

In [15]:
df.transmission_type.value_counts()

transmission_type
automatic           8266
manual              2935
automated_manual     626
direct_drive          68
unknown               19
Name: count, dtype: int64

# Q2 
- engine_hp and year
- engine_hp and engine_cylinders
- highway_mpg and engine_cylinders
- highway_mpg and city_mpg

In [16]:
np.corrcoef(df.engine_hp.values, df.year.values)

array([[1.        , 0.33871418],
       [0.33871418, 1.        ]])

In [17]:
np.corrcoef(df.engine_hp.values, df.engine_cylinders.values)

array([[1.        , 0.77485098],
       [0.77485098, 1.        ]])

In [18]:
np.corrcoef(df.highway_mpg.values, df.engine_cylinders.values)

array([[ 1.        , -0.61454142],
       [-0.61454142,  1.        ]])

In [19]:
np.corrcoef(df.highway_mpg.values, df.city_mpg.values)

array([[1.       , 0.8868295],
       [0.8868295, 1.       ]])

# Make price binary 

In [20]:
_avg = df.price.mean()

In [21]:
_avg

40594.737032063116

In [22]:
df['above_average'] = np.where(df['price'] > _avg, 1, 0)

In [23]:
df.head()

make       model  year  engine_hp  engine_cylinders transmission_type  \
0  bmw  1_series_m  2011      335.0               6.0            manual   
1  bmw    1_series  2011      300.0               6.0            manual   
2  bmw    1_series  2011      300.0               6.0            manual   
3  bmw    1_series  2011      230.0               6.0            manual   
4  bmw    1_series  2011      230.0               6.0            manual   

  vehicle_style  highway_mpg  city_mpg  price  above_average  
0         coupe           26        19  46135              1  
1   convertible           28        19  40650              1  
2         coupe           28        20  36350              0  
3         coupe           28        18  29450              0  
4   convertible           28        18  34500              0

In [24]:
df.head()

make       model  year  engine_hp  engine_cylinders transmission_type  \
0  bmw  1_series_m  2011      335.0               6.0            manual   
1  bmw    1_series  2011      300.0               6.0            manual   
2  bmw    1_series  2011      300.0               6.0            manual   
3  bmw    1_series  2011      230.0               6.0            manual   
4  bmw    1_series  2011      230.0               6.0            manual   

  vehicle_style  highway_mpg  city_mpg  price  above_average  
0         coupe           26        19  46135              1  
1   convertible           28        19  40650              1  
2         coupe           28        20  36350              0  
3         coupe           28        18  29450              0  
4   convertible           28        18  34500              0

# Split the data

In [25]:
from sklearn.model_selection import train_test_split

In [26]:
df_full_train, df_test = train_test_split(df, test_size=0.2, random_state=42)
df_train, df_val = train_test_split(df_full_train, test_size=0.25, random_state=42)

df_train = df_train.reset_index(drop=True)
df_val = df_val.reset_index(drop=True)
df_test = df_test.reset_index(drop=True)

y_train = df_train.price.values
y_val = df_val.price.values
y_test = df_test.price.values

del df_train['above_average']
del df_val['above_average']
del df_test['above_average']

In [27]:
from sklearn.metrics import mutual_info_score

In [28]:
df_full_train.head()

make      model  year  engine_hp  engine_cylinders  \
3181        cadillac        ct6  2016      265.0               4.0   
5357   mercedes-benz  gls-class  2017      449.0               8.0   
4874             kia      forte  2016      173.0               4.0   
8102           dodge    ram_250  1993      180.0               6.0   
10400        hyundai    tiburon  2008      172.0               6.0   

      transmission_type       vehicle_style  highway_mpg  city_mpg  price  \
3181          automatic               sedan           31        22  53495   
5357          automatic             4dr_suv           18        14  93850   
4874          automatic               coupe           34        25  19890   
8102             manual  regular_cab_pickup           16        11   2000   
10400         automatic       2dr_hatchback           24        17  21270   

       above_average  
3181               1  
5357               1  
4874               0  
8102               0  
10400              0

# Q3 
- make
- model
- transmission_type
- vehicle_style

In [29]:
def mutual_info_price_score(series):
    return mutual_info_score(series, df_full_train.above_average)

m_i = df_full_train[['make', 'model', 'transmission_type', 'vehicle_style']].apply(mutual_info_price_score)
m_i.sort_values(ascending=False).round(2)

model                0.46
make                 0.24
vehicle_style        0.08
transmission_type    0.02
dtype: float64

# Q4

In [30]:
features = [
    'make', 'model', 'year', 'engine_hp', 
    'engine_cylinders', 'transmission_type', 'vehicle_style', 'highway_mpg', 'city_mpg', 'price']

In [31]:
y_train_binarized = (y_train >= _avg).astype(int)
y_val_binarized = (y_val >= _avg).astype(int)
y_test_binarized = (y_test >= _avg).astype(int)

In [32]:
from sklearn.feature_extraction import DictVectorizer
from sklearn.linear_model import LogisticRegression

dv = DictVectorizer(sparse=False)

dicts_train = df_train[features].to_dict(orient='records')
X_train = dv.fit_transform(dicts_train)

val_dict = df_val[features].to_dict(orient='records')
X_val = dv.transform(val_dict)

In [33]:
model = LogisticRegression(solver='lbfgs', C=1.0, random_state=42, max_iter=1000, n_jobs=4)
model.fit(X_train, y_train_binarized)

LogisticRegression(max_iter=1000, n_jobs=4, random_state=42)

In [34]:
model.score(X_val,y_val_binarized).round(2)

1.0

# Q5

In [35]:
m_i = df_full_train[features].apply(mutual_info_price_score)
m_i.sort_values(ascending=False).round(3)

price                0.590
model                0.461
engine_hp            0.363
make                 0.239
engine_cylinders     0.117
vehicle_style        0.083
year                 0.074
city_mpg             0.059
highway_mpg          0.044
transmission_type    0.021
dtype: float64

In [36]:
def train_model(features):
    from sklearn.feature_extraction import DictVectorizer
    from sklearn.linear_model import LogisticRegression

    dv = DictVectorizer(sparse=False)

    dicts_train = df_train[features].to_dict(orient='records')
    X_train = dv.fit_transform(dicts_train)

    val_dict = df_val[features].to_dict(orient='records')
    X_val = dv.transform(val_dict)

    model = LogisticRegression(solver='lbfgs', C=1.0, random_state=42, max_iter=1000, n_jobs=4)
    model.fit(X_train, y_train_binarized)

    return model.score(X_val,y_val_binarized)

In [37]:
main_score = train_model(features)

In [38]:
scores = []
diffs = []
for n in range(len(features)):
    f = features.copy()
    f.pop(n)
    score = train_model(f)
    diff = round(main_score-score,4)
    scores.append(score)
    diffs.append(diff)

/home/sthz/miniconda3/envs/ml-zoomcamp/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [39]:
dict(zip(features,diffs))

{'make': 0.0,
 'model': 0.0,
 'year': 0.039,
 'engine_hp': 0.0,
 'engine_cylinders': 0.0,
 'transmission_type': 0.0,
 'vehicle_style': 0.0,
 'highway_mpg': 0.0,
 'city_mpg': -0.0004,
 'price': 0.0613}

# Q6

In [40]:
y_train_log = np.log1p(y_train)
y_val_log = np.log1p(y_val)
y_test_log = np.log1p(y_test)

In [41]:
from sklearn.linear_model import Ridge
from sklearn.metrics import mean_squared_error
RMSEprev=1
for a in [0, 0.01, 0.1, 1, 10]:
    clf = Ridge(alpha=a)
    clf.fit(X_train,y_train_log)
    y_pred=clf.predict(X_val)
    RMSE = mean_squared_error(y_val_log, y_pred, squared=False)
    if RMSE < RMSEprev:
        RMSEprev=RMSE
        best_alpha=a
    
    print(f'alpha {a} RMSE {RMSE.round(3)}') # To 0 is the best
print()
print(f'The best alpha is {best_alpha}')

alpha 0 RMSE 1142761520385.357
alpha 0.01 RMSE 0.293
alpha 0.1 RMSE 0.249
alpha 1 RMSE 0.229
alpha 10 RMSE 0.31

The best alpha is 1
